spring:
  application:
    name: vetech-reim
  datasource:
    url: jdbc:mysql://localhost:3306/vetech_reim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: scj20050720!?
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.spring.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

