spring:
  application:
    name: vetech-reim
  datasource:
    url: jdbc:mysql://localhost:3306/vetech_reim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: wtt123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

vetech:
  upload:
    path: ./uploads

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.spring.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

